resources:
  - name: di-authentication-api
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/di-authentication-api.git
      ignore_paths:
        - ci/pipeline.yaml
      branch: main

  - name: pipeline-src
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/di-authentication-api.git
      paths:
        - ci/pipeline.yaml
      branch: main

jobs:
  - name: update-pipeline
    plan:
      - get: pipeline-src
        trigger: true
      - set_pipeline: di-authentication-api
        file: pipeline-src/ci/pipeline.yaml

  - name: deploy-environment
    plan:
      - get: di-authentication-api
        trigger: true
      - task: build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gradle
              tag: 7.0.2-jdk11
          inputs:
            - name: di-authentication-api
          outputs:
            - name: lambda-zip
          run:
            path: /bin/bash
            args:
              - -euc
              - |
                cd di-authentication-api
                gradle --no-daemon :serverless:lambda:buildZip
                cp serverless/lambda/build/distributions/lambda.zip ../lambda-zip/

      - task: terraform-plan
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: 1.0.0
          params:
            DEPLOYER_ROLE_ARN: ((deployer-role-arn))
            BUILD_NOTIFY_API_KEY: ((build-notify-api-key))
            DEPLOY_ENVIRONMENT: test
          inputs:
            - name: lambda-zip
            - name: di-authentication-api
          outputs:
            - name: terraform-plan
          run:
            path: /bin/sh
            args:
              - -euc
              - |
                cd di-authentication-api/ci/terraform/aws
                terraform init -input=false \
                  -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
                  -backend-config "bucket=digital-identity-dev-tfstate" \
                  -backend-config "key=${DEPLOY_ENVIRONMENT}-terraform.tfstate" \
                  -backend-config "encrypt=true" \
                  -backend-config "region=eu-west-2"

                terraform plan \
                  -var 'lambda_zip_file=../../../../lambda-zip/lambda.zip' \
                  -var "deployer_role_arn=${DEPLOYER_ROLE_ARN}" \
                  -var "notify_api_key=${BUILD_NOTIFY_API_KEY}" \
                  -var "environment=${DEPLOY_ENVIRONMENT}" \
                  -out=../../../../terraform-plan/terraform.plan

      - task: terraform-apply
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: hashicorp/terraform
              tag: 1.0.0
          params:
            DEPLOYER_ROLE_ARN: ((deployer-role-arn))
            DEPLOY_ENVIRONMENT: test
          inputs:
            - name: lambda-zip
            - name: di-authentication-api
            - name: terraform-plan
          run:
            path: /bin/sh
            args:
              - -euc
              - |
                cd di-authentication-api/ci/terraform/aws
                terraform init -input=false \
                  -backend-config "role_arn=${DEPLOYER_ROLE_ARN}" \
                  -backend-config "bucket=digital-identity-dev-tfstate" \
                  -backend-config "key=${DEPLOY_ENVIRONMENT}-terraform.tfstate" \
                  -backend-config "encrypt=true" \
                  -backend-config "region=eu-west-2"

                terraform apply -auto-approve ../../../../terraform-plan/terraform.plan
